# Generated by Django 4.2.1 on 2023-10-20 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='роль пользователя')),
            ],
            options={
                'verbose_name': 'роль пользователя',
                'verbose_name_plural': 'роли пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='отчество')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='номер телефона')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userrole', verbose_name='роль пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, null=True, upload_to=users.models.image_product_directory_path, verbose_name='аватар')),
                ('alt', models.CharField(blank=True, max_length=50, null=True, verbose_name='описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'аватарка пользователя',
                'verbose_name_plural': 'аватарки пользователей',
            },
        ),
    ]
