# Generated by Django 4.2.1 on 2023-05-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Категория товара'),
            preserve_default=False,
        ),
    ]
