# Generated by Django 4.2.1 on 2023-05-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_productcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Роль пользователя'),
        ),
    ]
