# Generated by Django 4.2.1 on 2023-06-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Стоимость')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
    ]
