# Generated by Django 4.2.1 on 2023-06-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_productsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='subcategories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.productsubcategory', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
    ]
