# Generated by Django 4.2.1 on 2023-06-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_productcategory_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='subcategories',
        ),
    ]
