# Generated by Django 4.2.1 on 2023-06-27 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_remove_productcategory_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='frontend.productcategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
