# Generated by Django 4.2.1 on 2023-06-29 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_productsubcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Description product', max_length=500, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='freeDelivery',
            field=models.BooleanField(default=False, verbose_name='Бесплатная доставка'),
        ),
        migrations.AddField(
            model_name='product',
            name='fullDescription',
            field=models.TextField(default='Full description product', max_length=1000, verbose_name='Полное описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.productsubcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
    ]
