# Generated by Django 4.2.1 on 2023-07-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_product_description_product_freedelivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='', verbose_name='Путь')),
                ('alt', models.CharField(max_length=50, verbose_name='Описание')),
            ],
        ),
    ]
