# Generated by Django 4.2.1 on 2023-07-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageDepartments',
        ),
    ]
