# Generated by Django 4.2.1 on 2023-07-04 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_rename_image_imagedepartments'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='frontend.imagedepartments', verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
