# Generated by Django 4.2.1 on 2023-07-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_productcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedepartments',
            name='src',
            field=models.CharField(max_length=500, verbose_name='Путь'),
        ),
    ]
