# Generated by Django 4.2.1 on 2023-07-29 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_basket_order_orderstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.productcategory', verbose_name='Родительская категория'),
        ),
    ]
