# Generated by Django 4.2.1 on 2023-07-29 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_alter_productcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.productcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategories', to='frontend.productcategory', verbose_name='Родительская категория'),
        ),
        migrations.DeleteModel(
            name='ProductSubcategory',
        ),
    ]
