# Generated by Django 4.2.1 on 2023-07-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_alter_product_category_alter_productcategory_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='frontend.tag', verbose_name='Tags'),
        ),
    ]
