# Generated by Django 4.2.1 on 2023-07-31 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesproducts',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.product', verbose_name='Товар'),
        ),
    ]
