# Generated by Django 4.2.1 on 2023-08-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0032_remove_userprofile_avatar_useravatar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('text', models.CharField(max_length=500, verbose_name='Текст отзыва')),
                ('rate', models.IntegerField(verbose_name='Оценка')),
                ('created_to', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
