# Generated by Django 4.2.1 on 2023-08-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0034_reviewproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(default=[{}], verbose_name='Характеристики'),
            preserve_default=False,
        ),
    ]
