# Generated by Django 4.2.1 on 2023-08-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0035_product_specifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewproduct',
            options={'verbose_name': 'Отзыв о товаре', 'verbose_name_plural': 'Отзывы о товарах'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
    ]
