# Generated by Django 4.2.1 on 2023-10-20 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
            },
        ),
        migrations.CreateModel(
            name='ImageDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(blank=True, max_length=500, null=True, verbose_name='путь')),
                ('alt', models.CharField(blank=True, max_length=50, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'изображение категории товара',
                'verbose_name_plural': 'изображения категорий товара',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('fullName', models.CharField(blank=True, max_length=100, null=True, verbose_name='полное имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='номер телефона')),
                ('deliveryType', models.CharField(blank=True, max_length=20, null=True, verbose_name='тип доставки')),
                ('paymentType', models.CharField(blank=True, max_length=20, null=True, verbose_name='тип оплаты')),
                ('totalCost', models.FloatField(blank=True, null=True, verbose_name='полная стоимость')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='город')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'статус заказа',
                'verbose_name_plural': 'статаусы заказов',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='стоимость')),
                ('count', models.IntegerField(verbose_name='количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='наименование')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
                ('fullDescription', models.TextField(max_length=1000, verbose_name='полное описание')),
                ('freeDelivery', models.BooleanField(default=False, verbose_name='бесплатная доставка')),
                ('limited_edition', models.BooleanField(default=False, verbose_name='ограниченный тираж')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товар',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='тэг')),
            ],
            options={
                'verbose_name': 'тэг',
                'verbose_name_plural': 'тэги',
            },
        ),
        migrations.CreateModel(
            name='SpecificationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('value', models.CharField(max_length=100, verbose_name='значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='shop.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'характеристика товара',
                'verbose_name_plural': 'характеристики товаров',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.FloatField(verbose_name='цена со скидкой')),
                ('date_from', models.DateField(verbose_name='начало')),
                ('date_to', models.DateField(verbose_name='конец')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидки',
            },
        ),
        migrations.CreateModel(
            name='ReviewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='автор')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('text', models.CharField(max_length=500, verbose_name='текст отзыва')),
                ('rate', models.IntegerField(verbose_name='оценка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'отзыв о товаре',
                'verbose_name_plural': 'отзывы о товарах',
            },
        ),
        migrations.CreateModel(
            name='ProductsInOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.order', verbose_name='заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='товар')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInBaskets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='количество')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.basket', verbose_name='корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='товар')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='категория товара')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.imagedepartments', verbose_name='иконка')),
                ('parent', models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategories', to='shop.productcategory', verbose_name='родительская категория')),
            ],
            options={
                'verbose_name': 'категория продукта',
                'verbose_name_plural': 'категории товаров',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productcategory', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='shop.tag', verbose_name='тэги'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='shop.ProductsInOrders', to='shop.product', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.orderstatus', verbose_name='статус заказа'),
        ),
        migrations.CreateModel(
            name='ImagesProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=shop.models.image_product_directory_path, verbose_name='фото товара')),
                ('alt', models.CharField(default='Image alt string', max_length=50, verbose_name='описание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'изображение товара',
                'verbose_name_plural': 'изображения товара',
            },
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(through='shop.ProductsInBaskets', to='shop.product', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
